/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../common";
import type {
  ExampleExternalContract,
  ExampleExternalContractInterface,
} from "../ExampleExternalContract";

const _abi = [
  {
    inputs: [],
    name: "complete",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "completed",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getbalance",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052348015600f57600080fd5b5060c480601d6000396000f3fe60806040526004361060305760003560e01c80634d9b3d5d146035578063522e11771460545780639d9a7fe9146067575b600080fd5b348015604057600080fd5b506040514781526020015b60405180910390f35b60656000805460ff19166001179055565b005b348015607257600080fd5b50600054607f9060ff1681565b6040519015158152602001604b56fea2646970667358221220bf327a6e7b099f6f385cf307ef93e83a6c39f17146cfcc3762ede89274f5176064736f6c634300081c0033";

type ExampleExternalContractConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ExampleExternalContractConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ExampleExternalContract__factory extends ContractFactory {
  constructor(...args: ExampleExternalContractConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      ExampleExternalContract & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): ExampleExternalContract__factory {
    return super.connect(runner) as ExampleExternalContract__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ExampleExternalContractInterface {
    return new Interface(_abi) as ExampleExternalContractInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ExampleExternalContract {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as ExampleExternalContract;
  }
}
